name = "stats-check"
type = "javascript"
zone_id = ""
account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
route = ""
workers_dev = true
compatibility_date = "2022-02-15"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
